apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  ttlSecondsAfterFinished: 2
  template:
    spec:
      containers:
        - name: myjob
          image: centos
          command: ['/bin/bash','-c','sleep 100']
      restartPolicy: Never