apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
spec:
  template:
    spec:
      containers:
        - name: myjob
          image: centos
          command: ['/bin/bash','-c','sleep 3']
      restartPolicy: Never