apiVersion: v1
kind: PersistentVolume
metadata:
  name: labelfilesharetest
spec:
  capacity:
    storage: 5Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    readOnly: false
    volumeHandle: unique-volumeid  # make sure this volumeid is unique in the cluster
    volumeAttributes:
      resourceGroup: rg-viper-portal-dms-uat  # optional, only set this when storage account is not in the same resource group as agent node
      shareName: originshare
    nodeStageSecretRef:
      name: originfileshare1test
      namespace: default
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - cache=strict
    - nosharesock