apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labelfilesharedv
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: labelfilesharedv
  resources:
    requests:
      storage: 5Ti